// <auto-generated />
using System;
using HelpdeskApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HelpdeskApp.Migrations
{
    [DbContext(typeof(HelpdeskAppContext))]
    [Migration("20180717180243_AddSeedingData")]
    partial class AddSeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HelpdeskApp.Models.AssignmentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new { Id = 1, Name = "Desktop support" },
                        new { Id = 2, Name = "Helpdesk" },
                        new { Id = 3, Name = "Application support" }
                    );
                });

            modelBuilder.Entity("HelpdeskApp.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new { Id = 1, FullName = "Brad Bobley" },
                        new { Id = 2, FullName = "Bob Bradley" },
                        new { Id = 3, FullName = "Chris Crosby" }
                    );
                });

            modelBuilder.Entity("HelpdeskApp.Models.DataItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssignmentGroupId");

                    b.Property<int?>("ContactId");

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentGroupId");

                    b.HasIndex("ContactId");

                    b.ToTable("Items");

                    b.HasData(
                        new { Id = 1, AssignmentGroupId = 1, ContactId = 1, Description = "NullaPede.mov" },
                        new { Id = 2, AssignmentGroupId = 1, ContactId = 1, Description = "NecNisiVolutpat.ppt" },
                        new { Id = 3, AssignmentGroupId = 1, ContactId = 1, Description = "JustoPellentesque.tiff" },
                        new { Id = 4, AssignmentGroupId = 2, ContactId = 1, Description = "LobortisSapienSapien.xls" },
                        new { Id = 5, AssignmentGroupId = 2, ContactId = 2, Description = "ConsequatVarius.mp3" },
                        new { Id = 6, AssignmentGroupId = 2, ContactId = 2, Description = "BibendumMorbi.xls" },
                        new { Id = 7, AssignmentGroupId = 2, ContactId = 3, Description = "Parturient.tiff" },
                        new { Id = 8, AssignmentGroupId = 3, ContactId = 3, Description = "AugueVestibulum.pdf" },
                        new { Id = 9, AssignmentGroupId = 3, ContactId = 3, Description = "NibhLigula.png" },
                        new { Id = 10, AssignmentGroupId = 3, ContactId = 3, Description = "IpsumPrimisIn.jpeg" }
                    );
                });

            modelBuilder.Entity("HelpdeskApp.Models.DataItem", b =>
                {
                    b.HasOne("HelpdeskApp.Models.AssignmentGroup", "AssignmentGroup")
                        .WithMany("DataItems")
                        .HasForeignKey("AssignmentGroupId");

                    b.HasOne("HelpdeskApp.Models.Contact", "Contact")
                        .WithMany("DataItems")
                        .HasForeignKey("ContactId");
                });
#pragma warning restore 612, 618
        }
    }
}
